name: Tests

on: [push, pull_request]

jobs:

  linux:
    name: Test on Linux
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.2', '8.3', '8.4']

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: gmp

      - run: php -v
      - run: php -m
      - run: composer -V
      - run: composer install --no-progress
      - run: php vendor/bin/phpunit --no-coverage

  windows:
    name: Test on Windows
    defaults:
      run:
        shell: cmd
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.2', '8.3', '8.4']
        arch: [x64]
        ts: [nts]

    steps:
      - name: Setup PHP
        id: setup-php
        uses: php/setup-php-sdk@v0.11
        with:
          version: ${{matrix.php-version}}
          arch: ${{matrix.arch}}
          ts: ${{matrix.ts}}
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - run: php -v
      - run: echo extension=gmp>>C:\tools\php\php.ini
      - run: php -m
      - run: composer -V
      - run: composer install --no-progress
      - run: php vendor/bin/phpunit --no-coverage

  code_coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: gmp
          coverage: pcov

      - run: composer install --no-progress
      - run: mkdir -p build/logs
      - run: vendor/bin/phpunit --coverage-clover build/logs/clover.xml
      - run: wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.4.3/php-coveralls.phar
      - env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: php php-coveralls.phar --verbose
